### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by eabili0** [technagem/LeetCode#1]
Hello Daniel,

Referring to the go code for the TwoSum problem, I think there are two improvements to make:

1. You should be careful with your code formatting. There are Golang tools that assign an evaluation on your overall code quality and format is an important dimension. So I recommend the adoption of the `golint` package (https://github.com/golang/lint). If you are using VSCode, just install the Golang plugin;

2. Whenever you have the opportunity, do use the `testing` package for any Golang code you develop. This will ensure you get used to use this very important default Go package. You should then add a file called `TwoSum_test.go` with your tests in it and you will be able to use the `go test` command freely (https://golang.org/pkg/testing/). E.g.:

![image](https://user-images.githubusercontent.com/6494839/97095544-3bf73080-1637-11eb-8fa6-7b7548f27fe5.png)

**Comment by technagem** [comment]
Thanks for the feedback Abilio! Cheers!
